version: "3.3"

services:
  webapp:
    build: .
    restart: always
    environment:
      - SERVER_PORT=9090
      - SPRING_DATA_MONGODB_DATABASE=everyday
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
    ports:
      - "9090:9090"

  mongodb:
    image: mongo:latest
    restart: always
