version: "3.3"

services:
  webapp:
    build: .
    restart: always
    environment:
      - SPRING_DATA_MONGO_HOST=mongodb
      - SPRING_DATA_MONGO_PORT=27017
      - SPRING_DATA_MONGO_DATABASE=everyday

    ports:
      - "8081:8081"

  mongodb:
    image: mongo:latest
    restart: always


